require('dotenv').config();

const MODELS = [
  { slug: 'camila', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white woman, 22 years old, slim toned natural body, long straight dark brown hair with subtle highlights falling past shoulders, warm honey-brown eyes, light golden skin with warm undertones, small straight nose, full natural lips, high cheekbones, oval face shape, zero makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'beatriz', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white woman, 26 years old, slim lean body, medium-length wavy blonde hair with beachy texture at shoulder level, light brown eyes, fair skin with warm rosy undertones, delicate freckles on nose and cheeks, straight nose, naturally full lips, soft jawline, heart-shaped face, minimal natural makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'jessica', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black woman, 23 years old, slim toned body with natural curves, voluminous natural curly afro hair, dark brown almond-shaped eyes with long natural lashes, deep rich dark brown skin with cool undertones, broad flat nose, full well-defined lips, prominent cheekbones, round face shape, no makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'aline', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black woman, 28 years old, slim athletic body, shoulder-length box braids with golden tips, dark brown eyes, warm medium-dark brown skin with golden undertones, wide nose, full naturally dark lips, strong jawline, oval face shape, minimal natural makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'fernanda', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white woman, 24 years old, plus size full figured body with soft curves, natural belly, full thighs and arms, long wavy chestnut brown hair falling past shoulders, warm hazel eyes, light olive skin with warm undertones, soft round nose, full lips, round full face with soft cheeks, dimples, minimal natural makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'larissa', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white woman, 29 years old, plus size curvy body with natural softness, full figure with generous bust and hips, long straight black hair with slight shine, dark brown eyes, light skin with neutral undertones, button nose, defined full lips, square jaw, round full face, natural no-makeup look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'bruna', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black woman, 25 years old, plus size full figured body with beautiful natural curves, generous bust, full hips and thighs, long goddess locs hairstyle, dark brown eyes with natural lashes, deep chocolate brown skin with warm undertones, wide flat nose, full naturally dark lips, round full face with prominent cheekbones, minimal natural makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'tatiane', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black woman, 27 years old, plus size curvy body with natural fullness, large bust and full rounded hips, short natural 4C coily hair, deep dark brown eyes, very dark ebony skin with blue-black undertones, broad nose, full dark lips, oval full face with strong cheekbones, natural glowing no-makeup look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'sandra', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature elegant Brazilian white woman, 55 years old, slim toned body with graceful posture, short pixie cut silver-gray hair with natural texture, light blue-gray eyes, fair skin with natural age lines and laugh lines adding character, age spots naturally present, soft but defined facial structure, thin lips with natural aging, slim straight nose, oval mature face, sophisticated minimal makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'marcia', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature elegant Brazilian white woman, 62 years old, slim body with refined posture, medium-length salt and pepper wavy hair, warm brown eyes with fine lines around them, light skin with visible natural aging, prominent cheekbones, defined jawline with slight softening, thin nose, refined lips, square mature face, elegant natural makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'rosangela', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature elegant Brazilian Black woman, 53 years old, slim toned body with graceful posture, short natural gray-streaked afro hair, deep brown eyes with natural maturity lines, rich dark brown skin with warm undertones, beautiful natural aging with defined character lines, broad nose, full lips, prominent mature cheekbones, oval face with distinguished mature features, minimal natural makeup, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'conceicao', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature distinguished Brazilian Black woman, 60 years old, slim elegant body, medium natural afro with beautiful silver-white streaks throughout, dark brown deep-set eyes with graceful age lines, deep ebony skin with cool blue undertones, natural aging lines adding dignity, wide nose, full naturally dark lips, strong mature cheekbones, round face with distinguished mature features, clean natural no-makeup look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'gabriel', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white man, 24 years old, slim athletic build with toned muscles, short neat dark brown hair with slight fade on sides, light brown eyes, light skin with warm golden undertones, straight nose, defined jawline with light stubble, strong chin, rectangular face shape, natural look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'rafael', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white man, 28 years old, slim lean build, short curly dark brown hair with natural texture, green-hazel eyes, fair skin with light freckles on nose, straight defined nose, clean shaven smooth face, angular jawline, square face shape, natural look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'matheus', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black man, 23 years old, slim athletic muscular build, short natural low-cut black hair with tight curls, dark brown deep eyes, rich warm dark brown skin with golden undertones, broad nose, full lips, strong defined jawline, oval face shape with prominent cheekbones, clean shaven, natural look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'diego', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black man, 27 years old, slim toned build with defined arms, short afro fade haircut, very dark brown almost black eyes, deep ebony skin with cool undertones, wide flat nose, full dark lips, sharp strong jawline, light short beard, square face shape, natural confident look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'bruno', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white man, 25 years old, plus size stocky heavy-set build with natural belly, broad shoulders, full arms and legs, short straight light brown hair, blue eyes, fair skin with neutral undertones, soft round nose, full lips, round full face with soft cheeks, light beard stubble, natural look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'rodrigo', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian white man, 29 years old, plus size large body build, full belly and broad frame, thick arms, short dark hair with slight wave, dark brown eyes, light olive skin with warm undertones, straight nose, full lips, round face with soft features, short trimmed beard, natural look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'anderson', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black man, 26 years old, plus size large heavy-set build with natural belly, broad chest and shoulders, full thick arms, short natural low-cut afro, dark brown eyes, deep rich chocolate brown skin with warm undertones, broad nose, full dark lips, round full face with prominent cheekbones, clean shaven, natural confident look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'leandro', prompt: 'Hyperrealistic professional fashion photography, full body shot, young Brazilian Black man, 28 years old, plus size stocky muscular heavy build, large frame with natural fullness, short afro fade with tight curls, very dark ebony skin with blue-black undertones, wide nose, full lips, strong jaw with light beard, oval full face, natural look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed confident upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture with natural pores, real hair strands, fabric texture visible, professional fashion editorial, body positive, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'carlos', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature distinguished Brazilian white man, 55 years old, slim elegant body with upright posture, short neat silver-gray hair combed to the side, light gray-blue eyes with natural age lines, fair skin with natural aging wrinkles and character lines, defined cheekbones, straight refined nose, thin lips, strong mature jawline, rectangular face shape, short neat silver beard stubble, natural sophisticated look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'paulo', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature distinguished Brazilian white man, 63 years old, slim body with graceful posture, short salt and pepper hair neatly trimmed, warm brown eyes with pronounced age lines and crow feet, light skin with visible natural wrinkles adding dignity, prominent cheekbones, straight nose, defined lips, strong mature jawline, clean shaven, square mature face, natural distinguished look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'antonio', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature distinguished Brazilian Black man, 54 years old, slim elegant body with strong upright posture, short low-cut natural gray-streaked black hair, deep dark brown eyes with natural mature age lines, rich dark brown skin with warm undertones, natural aging adding dignity and character, broad nose, full lips, strong mature jawline, short neat salt and pepper beard, oval face with prominent mature cheekbones, natural distinguished look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
  { slug: 'benedito', prompt: 'Hyperrealistic professional fashion photography, full body shot, mature distinguished Brazilian Black man, 60 years old, slim body with refined posture, completely bald head with natural shine, dark brown deep-set eyes with graceful wrinkles, deep ebony skin with cool blue-black undertones, beautiful natural aging with strong character lines, wide flat nose, full dark lips, very strong defined mature jawline, short full white-gray beard, strong square face shape, natural distinguished dignified look, wearing a plain fitted white crew-neck t-shirt and plain straight-leg black trousers, simple white sneakers, standing relaxed elegant upright facing camera, arms resting naturally at sides, pure seamless white studio background, soft diffused studio lighting, 85mm portrait lens, shallow depth of field, ultra sharp focus on face and full body, photorealistic skin texture, real hair strands, fabric texture visible, professional fashion editorial, Canon EOS R5, f/2.8, ISO 100' },
];

async function generateModel(model) {
  console.log(`\n🎨 Gerando: ${model.slug}...`);

  try {
    // Submit
    const res = await fetch('https://queue.fal.run/fal-ai/flux-pro/v1.1-ultra', {
      method: 'POST',
      headers: {
        'Authorization': 'Key ' + process.env.FAL_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        prompt: model.prompt,
        image_size: 'portrait_4_3',
        num_inference_steps: 28,
        enable_safety_checker: false,
        raw: true
      })
    });

    const data = await res.json();
    if (!data.request_id) {
      console.error(`❌ ${model.slug}: Erro no submit:`, JSON.stringify(data));
      return null;
    }

    // Poll
    for (let i = 0; i < 60; i++) {
      await new Promise(r => setTimeout(r, 5000));
      const poll = await fetch(data.status_url, {
        headers: { 'Authorization': 'Key ' + process.env.FAL_API_KEY }
      });
      const result = await poll.json();

      if (result.status === 'COMPLETED') {
        const final = await fetch(data.response_url, {
          headers: { 'Authorization': 'Key ' + process.env.FAL_API_KEY }
        });
        const finalData = await final.json();
        const url = finalData.images?.[0]?.url;
        console.log(`✅ ${model.slug}: ${url}`);
        return { slug: model.slug, url };
      }

      if (result.status === 'FAILED') {
        console.error(`❌ ${model.slug}: Falhou`);
        return null;
      }

      process.stdout.write('.');
    }

    console.error(`❌ ${model.slug}: Timeout`);
    return null;

  } catch (err) {
    console.error(`❌ ${model.slug}: Erro:`, err.message);
    return null;
  }
}

async function main() {
  console.log('🚀 Iniciando geração das 24 modelos...');
  console.log('⏱️  Tempo estimado: ~15-20 minutos');
  console.log('💰 Custo estimado: ~$1.44 total\n');

  const results = [];

  // Gera uma de cada vez para não sobrecarregar a API
  for (const model of MODELS) {
    const result = await generateModel(model);
    if (result) results.push(result);
    // Pausa de 2s entre cada geração
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log('\n\n📋 RESULTADO FINAL:');
  console.log('==================');
  results.forEach(r => console.log(`${r.slug}: ${r.url}`));
  console.log(`\n✅ ${results.length}/24 modelos gerados com sucesso`);
}

main().catch(console.error);
