require('dotenv').config();

const MODELS = [
  { slug: 'beatriz', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white woman, 26 years old, slim lean body, medium-length wavy blonde hair with natural beach texture and individual strands catching studio light, light brown eyes with visible iris texture and natural catchlight, fair skin with warm rosy undertones, visible natural pores, delicate freckles on nose and cheeks, natural skin imperfections, straight nose, naturally full lips, soft jawline, heart-shaped face, zero makeup, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, natural shadow under nose and chin, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, no filters, RAW unedited photograph' },
  { slug: 'jessica', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black woman, 23 years old, slim toned body with natural curves, voluminous natural curly afro hair with individual curl texture visible, dark brown almond-shaped eyes with visible iris detail and long natural lashes, deep rich dark brown skin with cool undertones, visible natural skin texture and pores, broad flat nose with natural skin detail, full well-defined lips, prominent cheekbones, round face shape, no makeup, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, natural shadow under nose and chin, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, no filters, RAW unedited photograph' },
  { slug: 'aline', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black woman, 28 years old, slim athletic body, shoulder-length box braids with golden tips and individual braid texture visible, dark brown eyes with natural iris reflections, warm medium-dark brown skin with golden undertones, visible natural skin texture and pores, wide nose with natural skin detail, full naturally dark lips, strong jawline, oval face, minimal natural look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, natural shadow under nose and chin, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, no filters, RAW unedited photograph' },
  { slug: 'fernanda', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white woman, 24 years old, plus size full figured body with soft natural curves, natural belly, long wavy chestnut brown hair with individual strands catching light, warm hazel eyes with visible iris texture, light olive skin with warm undertones, visible natural pores and skin texture, soft round nose, full lips, round full face with soft cheeks and dimples, minimal natural makeup, plain white fitted crew-neck t-shirt with natural fabric wrinkles fitting her curves, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'larissa', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white woman, 29 years old, plus size curvy body with natural fullness, generous bust and hips, natural belly, long straight black hair with natural shine and individual strands, dark brown eyes with natural reflections and visible iris detail, light skin with neutral undertones, visible natural pores and skin texture, button nose, defined full lips, square jaw, round face, natural no-makeup look, plain white fitted crew-neck t-shirt with natural wrinkles fitting her curves, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'bruna', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black woman, 25 years old, plus size full figured body with beautiful natural curves, generous bust and full hips, long goddess locs hairstyle with natural hair texture visible, dark brown eyes with natural iris detail and natural lashes, deep chocolate brown skin with warm golden undertones, visible natural skin texture and pores, wide flat nose with skin detail, full naturally dark lips, round full face with prominent cheekbones and soft cheeks, natural no-makeup look, plain white fitted crew-neck t-shirt with natural wrinkles fitting her curves, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'tatiane', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black woman, 27 years old, plus size curvy body with natural fullness, large bust and full rounded hips, short natural 4C coily hair with individual curl texture visible, deep dark brown eyes with natural lashes and iris detail, very dark ebony skin with blue-black undertones, visible natural skin texture and luminosity, broad nose with natural skin detail, full dark lips with natural pigmentation, oval full face with strong cheekbones, natural glowing skin no-makeup, plain white fitted crew-neck t-shirt with natural wrinkles fitting her curves, plain straight-leg black trousers, standing relaxed facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'sandra', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature elegant Brazilian white woman, 55 years old, slim toned body with graceful posture, short pixie cut silver-gray hair with natural texture and individual strands visible, light blue-gray eyes with visible iris detail and natural mature crow feet lines, fair skin with natural visible age lines and laugh lines that add character, slight age spots naturally present, slim straight nose with skin texture, thin lips with natural aging lines, oval mature face, sophisticated minimal makeup, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'marcia', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature elegant Brazilian white woman, 62 years old, slim body with refined posture, medium-length salt and pepper wavy hair with individual strands visible, warm brown eyes with fine lines around them and natural iris detail, light skin with visible natural aging wrinkles and character lines, prominent cheekbones, defined jawline with slight softening, refined lips, square mature face, elegant natural makeup, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'rosangela', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature elegant Brazilian Black woman, 53 years old, slim toned body with graceful posture, short natural gray-streaked afro hair with individual curl texture visible, deep brown eyes with natural maturity lines and visible iris detail, rich dark brown skin with warm undertones, natural aging with defined character lines, broad nose with natural skin detail, full lips with natural dark pigmentation, prominent mature cheekbones, oval mature face, minimal natural makeup, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'conceicao', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature distinguished Brazilian Black woman, 60 years old, slim elegant body, medium natural afro with beautiful silver-white streaks throughout and individual curl texture visible, dark brown deep-set eyes with graceful age lines and natural iris detail, deep ebony skin with cool blue undertones, natural aging lines adding dignity and character, wide nose, full naturally dark lips, strong mature cheekbones, round face with distinguished mature features, clean natural no-makeup look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'gabriel', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white man, 24 years old, slim athletic build with toned muscles, short neat dark brown hair with slight fade on sides and individual strands visible, light brown eyes with visible iris detail and natural catchlight, light skin with warm golden undertones, visible natural pores and skin texture, straight nose, defined jawline with light stubble, strong chin, rectangular face shape, natural no-makeup look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed confident facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'rafael', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white man, 28 years old, slim lean build, short curly dark brown hair with natural texture and individual strands, green-hazel eyes with visible iris detail, fair skin with light freckles on nose, visible natural pores, straight defined nose, clean shaven smooth face, angular jawline, square face shape, natural look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed confident facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'matheus', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black man, 23 years old, slim athletic muscular build, short natural low-cut black hair with tight curls, dark brown deep eyes with visible iris detail and natural catchlight, rich warm dark brown skin with golden undertones, visible natural skin texture and pores, broad nose with natural skin detail, full lips, strong defined jawline, oval face shape with prominent cheekbones, clean shaven, natural look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed confident facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'diego', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black man, 27 years old, slim toned build with defined arms, short afro fade haircut with individual hair texture visible, very dark brown almost black eyes with visible iris detail, deep ebony skin with cool undertones, visible natural skin texture and pores, wide flat nose, full dark lips, sharp strong jawline, light short beard, square face shape, natural confident look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed confident facing camera, slight natural weight shift, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'bruno', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white man, 25 years old, plus size stocky heavy-set build with natural belly, broad shoulders, short straight light brown hair with individual strands, blue eyes with visible iris detail, fair skin with neutral undertones, visible natural pores and skin texture, soft round nose, full lips, round full face with soft cheeks, light beard stubble, natural look, plain white fitted crew-neck t-shirt with natural fabric wrinkles fitting his frame, plain straight-leg black trousers, standing relaxed confident facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'rodrigo', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian white man, 29 years old, plus size large body build, full belly and broad frame, short dark hair with slight wave and individual strands, dark brown eyes with visible iris detail, light olive skin with warm undertones, visible natural pores and skin texture, straight nose, full lips, round face with soft features, short trimmed beard, natural look, plain white fitted crew-neck t-shirt with natural fabric wrinkles fitting his frame, plain straight-leg black trousers, standing relaxed confident facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'anderson', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black man, 26 years old, plus size large heavy-set build with natural belly, broad chest and shoulders, short natural low-cut afro with individual curl texture visible, dark brown eyes with visible iris detail, deep rich chocolate brown skin with warm undertones, visible natural skin texture and pores, broad nose with skin detail, full dark lips, round full face with prominent cheekbones, clean shaven, natural confident look, plain white fitted crew-neck t-shirt with natural fabric wrinkles fitting his frame, plain straight-leg black trousers, standing relaxed confident facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'leandro', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, young Brazilian Black man, 28 years old, plus size stocky muscular heavy build, large frame with natural fullness, short afro fade with tight curls and individual hair texture, very dark ebony skin with blue-black undertones, visible natural skin texture and pores, wide nose, full lips, strong jaw with light beard, oval full face, natural look, plain white fitted crew-neck t-shirt with natural fabric wrinkles fitting his frame, plain straight-leg black trousers, standing relaxed confident facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'carlos', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature distinguished Brazilian white man, 55 years old, slim elegant body with upright posture, short neat silver-gray hair combed to the side with individual strands visible, light gray-blue eyes with natural age lines and visible iris detail, fair skin with natural aging wrinkles and character lines, defined cheekbones, straight refined nose, thin lips, strong mature jawline, rectangular face shape, short neat silver beard stubble, natural sophisticated look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'paulo', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature distinguished Brazilian white man, 63 years old, slim body with graceful posture, short salt and pepper hair neatly trimmed with individual strands visible, warm brown eyes with pronounced age lines and visible iris detail, light skin with visible natural wrinkles adding dignity, prominent cheekbones, straight nose, defined lips, strong mature jawline, clean shaven, square mature face, natural distinguished look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'antonio', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature distinguished Brazilian Black man, 54 years old, slim elegant body with strong upright posture, short low-cut natural gray-streaked black hair with individual hair texture visible, deep dark brown eyes with natural mature age lines and visible iris detail, rich dark brown skin with warm undertones, natural aging adding dignity and character, broad nose with skin detail, full lips with natural dark pigmentation, strong mature jawline, short neat salt and pepper beard, oval face with prominent mature cheekbones, natural distinguished look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
  { slug: 'benedito', prompt: 'Three-quarter shot from head to knees, unretouched portrait_studio_20240815_0042.CR2, mature distinguished Brazilian Black man, 60 years old, slim body with refined posture, completely bald head with natural skin texture and shine, dark brown deep-set eyes with graceful wrinkles and visible iris detail, deep ebony skin with cool blue-black undertones, natural aging with strong character lines and visible skin texture, wide flat nose, full dark lips, very strong defined mature jawline, short full white-gray beard with individual hair texture, strong square face shape, natural distinguished dignified look, plain white fitted crew-neck t-shirt with subtle natural fabric wrinkles, plain straight-leg black trousers, standing relaxed elegant facing camera, arms loose at sides, pure seamless white studio background, single key light at 45 degrees upper left, subtle fill light from right, Canon EOS R5, 85mm f/1.4 lens, ISO 400, 1/200s shutter speed, natural color profile, no retouching, RAW unedited photograph' },
];

async function generateModel(model) {
  console.log(`\n🎨 Gerando: ${model.slug}...`);
  try {
    const res = await fetch('https://queue.fal.run/fal-ai/flux-pro/v1.1-ultra', {
      method: 'POST',
      headers: {
        'Authorization': 'Key ' + process.env.FAL_API_KEY,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        prompt: model.prompt,
        image_size: 'portrait_4_3',
        num_inference_steps: 45,
        guidance_scale: 2.2,
        enable_safety_checker: false,
        raw: true
      })
    });

    const data = await res.json();
    if (!data.request_id) {
      console.error(`❌ ${model.slug}:`, JSON.stringify(data));
      return null;
    }

    for (let i = 0; i < 60; i++) {
      await new Promise(r => setTimeout(r, 6000));
      const poll = await fetch(data.status_url, {
        headers: { 'Authorization': 'Key ' + process.env.FAL_API_KEY }
      });
      const result = await poll.json();

      if (result.status === 'COMPLETED') {
        const final = await fetch(data.response_url, {
          headers: { 'Authorization': 'Key ' + process.env.FAL_API_KEY }
        });
        const finalData = await final.json();
        const url = finalData.images?.[0]?.url;
        console.log(`✅ ${model.slug}: ${url}`);
        return { slug: model.slug, url };
      }
      if (result.status === 'FAILED') {
        console.error(`❌ ${model.slug}: Falhou`);
        return null;
      }
      process.stdout.write('.');
    }
    console.error(`❌ ${model.slug}: Timeout`);
    return null;
  } catch (err) {
    console.error(`❌ ${model.slug}:`, err.message);
    return null;
  }
}

async function main() {
  console.log('🚀 Gerando 23 modelos com template v5 (three-quarter + realismo máximo)...');
  console.log('💰 Custo estimado: ~$1.38');
  console.log('⏱️  Tempo estimado: ~20-25 minutos\n');

  const results = [];
  for (const model of MODELS) {
    const result = await generateModel(model);
    if (result) results.push(result);
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log('\n\n📋 SQL PARA ATUALIZAR NO SUPABASE:');
  console.log('=====================================');
  results.forEach(r => {
    console.log(`UPDATE preset_models SET reference_url = '${r.url}' WHERE slug = '${r.slug}';`);
  });
  console.log(`\n✅ ${results.length}/23 geradas com sucesso`);
}

main().catch(console.error);
